eureka:
  security:
    username: admin
    password: admin
  client:
    serviceUrl:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@127.0.0.1:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
