eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
