my-config:
  my-name: chenjian

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hello-server
          uri: lb://hello-server
          predicates:
            - Path=/hello-server/**
          filters:
            - StripPrefix=1
        - id: hello-client
          uri: lb://hello-client
          predicates:
            - Path=/hello-client/**
          filters:
            - StripPrefix=1

